"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BottomNav from "./component/bottombar";
import { Sidebar } from "./component/sidebar";
import { useState } from "react";
import { Hometab } from "./component/hometab";
import { Project } from "./component/Project";
import { About } from "./component/about";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [activeTab, setActiveTab] = useState("home");

  const renderTabContent = () => {
    switch (activeTab) {
      case "home":
        return <Hometab setActiveTab={setActiveTab} />;
      case "project":
        return <Project setActiveTab={setActiveTab} />;
      case "about":
        return <About setActiveTab={setActiveTab} />;
      default:
        return children;
    }
  };

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Sidebar />
        <main className="min-h-screen">{renderTabContent()}</main>
        <BottomNav activeTab={activeTab} setActiveTab={setActiveTab} />
      </body>
    </html>
  );
}
